routes/web.php
<?php

use App\Http\Controllers\categoriesController;
use App\Http\Controllers\postsController;
use App\Http\Controllers\usersController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/blog/category/{category}', 'WelcomeController@category')->name('blogs.category');
Route::get('/blog/tag/{tag}', 'WelcomeController@tag')->name('blogs.tag');
Route::get('/blog/post/{post}', 'WelcomeController@post')->name('blogs.post');

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'categoriesController');
    Route::resource('posts', 'postsController');
    Route::resource('tags', 'tagsController');

    // Route for soft delete:

    Route::delete('/trash/{post}', 'postsController@trash')->name('posts.trash');

    // index of trashes posts

    Route::get('/trashed', 'postsController@trashed')->name('posts.trashed');

    // restore

    Route::put('/restore/{post}', 'postsController@restore')->name('posts.restore');
});


Route::middleware(['auth', 'verifyAdmin'])->group(function () {
    Route::get('/users', 'usersController@index')->name('users.index');
    Route::put('/users/{user}/make-admin', 'usersController@makeAdmin')->name('users.make-admin');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    //
    protected  $fillable = ['name'];

    // relationship functions
    public function posts()
    {
        return $this->belongsToMany(Post::class)->withTimestamps();
    }
}

app/Http/Controllers/tagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;
use Illuminate\Http\Request;

class tagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //(

        $tags = Tag::all();
        return view('tags.index', compact([
            'tags'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        //
        // to store the data in database we have to follow 3 steps:
        // 1. To validate the data ->done (we validated the data using Request class)

        // 2. Store the data in database
        Tag::create([
            'name' => $request->name
        ]);

        // Session set something and then return the view:
        session()->flash('success', 'Tag Added Successfully!');
        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        //
        return view('tags.create', [
            'tag' => $tag
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        //
        $tag->name = $request->input('name');
        $tag->save();
        session()->flash('success', "Tag updated successfully");
        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        //
        if ($tag->posts->count() > 0) {
            session()->flash('error', 'This Tag can not be deleted as some posts are associated with it');
            return redirect()->back();
        }
        $tag->delete();
        session()->flash('success', "Tag Deleted Successfully");
        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app');

@section('content')

<div class="card">

    <div class="card-header">
        @if(isset($tag))
            Edit Tag
        @else
            Add Tag
        @endif
    </div>

    <div class="card-body">
        <form action="{{ (isset($tag)) ?  route('tags.update', $tag->id): route('tags.store') }}" method="POST">
            @csrf

            @if(isset($tag))
                @method('PUT')
            @endif

            <div class="form-group">

                <label for="name">Name</label>

                <input type="text"
                value= "{{ isset($tag) ? $tag->name : ''}}"
                class="form-control @error('name') is-invalid @enderror"
                name="name" id="name">

                @error('name')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>

            <div class="form-group">
                <button class="btn btn-success" type="submit">
                    Add Tag</button>
            </div>
        </form>
    </div>

</div>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')



@section('content')

@include('layouts._message')
<div class="d-flex justify-content-end mb-3">
    <a href="{{ route('tags.create') }}" class="btn btn-primary">Add Tag</a>
</div>

<div class="card">
    <div class="card-header">Tags</div>
    <div class="card-body">
        {{-- Table to show is to be created here! --}}

        <table class="table tale-bordered">
            <thead>
                <th>Name</th>
                <th>Posts Count</th>
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach($tags as $tag)
                    <tr>
                        <td>{{$tag->name}}</td>
                        <td>{{$tag->posts->count()}}</td>
                        <td><a href="{{route('tags.edit',$tag->id)}}" class="btn btn-warning btn-sm">Edit</a>
                        <a href="#" onclick="displayModalForm({{$tag}})"
                         class="btn btn-danger btn-sm"

                            data-toggle="modal"
                            data-target="#deleteModal">Delete</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

{{-- DELETE MODAL --}}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form action="" method="POST" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
                <p>Are you sure you want to delete tag</p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
        </div>
    </div>
  </div>
{{-- END DELETE MODAL --}}
@endsection



@section('page-level-scripts')
  <script type= "text/javascript">



    function displayModalForm($tag)
    {
        var url = '/tags/' + $tag.id;
        $('#deleteForm').attr('action',url);
    }
</script>
@endsection