routes/web.php
<?php

use App\Http\Controllers\categoriesController;
use App\Http\Controllers\postsController;
use App\Http\Controllers\usersController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/blog/category/{category}', 'WelcomeController@category')->name('blogs.category');
Route::get('/blog/tag/{tag}', 'WelcomeController@tag')->name('blogs.tag');
Route::get('/blog/post/{post}', 'WelcomeController@post')->name('blogs.post');

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'categoriesController');
    Route::resource('posts', 'postsController');
    Route::resource('tags', 'tagsController');

    // Route for soft delete:

    Route::delete('/trash/{post}', 'postsController@trash')->name('posts.trash');

    // index of trashes posts

    Route::get('/trashed', 'postsController@trashed')->name('posts.trashed');

    // restore

    Route::put('/restore/{post}', 'postsController@restore')->name('posts.restore');
});


Route::middleware(['auth', 'verifyAdmin'])->group(function () {
    Route::get('/users', 'usersController@index')->name('users.index');
    Route::put('/users/{user}/make-admin', 'usersController@makeAdmin')->name('users.make-admin');
});

app/Post.php
<?php

namespace App;

use App\Http\Middleware\verifyCategoriesCount;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{


    use SoftDeletes; //it is a trait which add additional methods related to soft delete such as delete,forceDelete and restore:
    //fillable for maas assigment:

    protected $dates = ['published_at'];
    protected $fillable =  [
        'title',
        'excerpt',
        'user_id',
        'content',
        'image',
        'category_id',
        'published_at'
    ];

    // This function is used to delete the file(image) from local storage during delete and updation of post.
    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id'); //second argument is to specify the foreign key as we have changed the name of the function fri user to author:
    }
}

app/Http/Controllers/postsController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use App\Http\Requests\posts\CreatePostRequest;
use App\Http\Requests\posts\UpdatePostRequest;
use App\Category;
use App\Tag;

class postsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware(['verifyCategoriesCount'])->only('create', 'store');
        $this->middleware(['verifyAuthor'])->only('edit', 'update', 'destroy', 'trash');
    }
    public function index()
    {
        //

        if (!auth()->user()->isAdmin()) {
            $posts = Post::withoutTrashed()->where('user_id', auth()->id())->paginate(10);
        } else {
            $posts = Post::paginate(10);
        }
        return view('posts.index', [
            'posts' => $posts
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        $categories = Category::all();
        $tags = Tag::all();

        return view('posts.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request)
    {

        //image upload and stores the name of the image:
        $image = $request->file('image')->store('posts'); //this line will result in to store the images in to storage folder inside storage
        //run the command :php artisan storage:link


        $post = Post::create([
            'title' => $request->title,
            'excerpt' => $request->excerpt,
            'content' => $request->content,
            'image' => $image,
            'user_id' => auth()->id(),
            'category_id' => $request->category_id,
            'published_at' => now() //TODO have to set timezone.

        ]);

        $post->tags()->attach($request->tags);
        session()->flash('success', 'Post has been successfully created!');
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        //
        $data = $request->only(['title', 'excerpt', 'content', 'published_at', 'category_id']);


        if ($request->hasFile('image')) {
            //store the image and delete the old image:
            $image = $request->image->store('posts');
            $post->deleteImage();
            $data['image'] = $image;
        }

        $post->update($data);

        $post->tags()->sync($request->tags);
        session()->flash('success', 'Post has been updated successfully!');
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //ider post ka object seeda nhi mil payaga q ke soft delete hai na voh toh humko iske id se iska object lana padaga iske model binding nhi ho payage:
        $post = Post::onlyTrashed()->findOrFail($id);
        $post->deleteImage();
        $post->forceDelete();
        session()->flash('success', 'Post Deleted Successfully!');
        return redirect()->back(); //Create a new redirect response to the previous location.
    }

    // soft deletes the posts
    public function trash(Post $post)
    {
        //TODO if post will soft delete then also category will not be deletd
        $post->delete(); //This will do soft-delete
        session()->flash('success', 'Post trashed successfully!');
        return redirect(route('posts.index'));
    }

    // function for showing all the trashed(soft-deleted) posts.
    public function trashed()
    {
        // $trashed = DB::table('posts')->whereNotNull('deleted_at');
        $trashed = Post::onlyTrashed()->paginate(10);
        return view('posts.trashed')->with('posts', $trashed); //with: adds a piece of data to the view
    }

    // function to restore the post
    public function restore($id)
    {
        $trashedPost = Post::onlyTrashed()->findOrFail($id);
        $trashedPost->restore();
        session()->flash('success', "Post has been restored successfully!");
        return redirect(route('posts.index'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app');

@section('content')

<div class="card">
    <div class="card-header">Add Post</div>

    <div class="card-body">
        <form action="{{route('posts.store')}}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="form-group">

                <label for="title">Title</label>

                <input type="text"
                class="form-control @error('title') is-invalid @enderror"
                value = "{{old('title')}}"
                name="title" id="title">

                @error('title')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>


            <div class="form-group">

                <label for="name">Excerpt</label>

                <textarea
                name="excerpt"
                id="excerpt"
                rows="4"
                class="form-control @error('excerpt') is-invalid @enderror">{{old('excerpt')}}</textarea>

                @error('excerpt')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>


            <div class="form-group">

                <label for="content">Content</label>

                <input id="content" type="hidden" name="content">
                <trix-editor input="content"></trix-editor>
                @error('content')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>

            <div class="form-group">
                <select class="form-control select2" name="category_id" id="category_id">

                    <option value="-1" disabled selected>select...</option>
                    @foreach($categories as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach

                </select>
            </div>

            <div class="form-group">
                <select class="form-control select2" name="tags[]" id="tags"  multiple="multiple">

                    @foreach($tags as $tag)
                        <option value="{{$tag->id}}">{{$tag->name}}</option>
                    @endforeach

                </select>

            </div>
            <div class="form-group">
                <label for="published_at">Published At</label>
                <input type="date"
                value = "{{old('published_at')}}"
                class="form-control"
                name="published_at" id="published_at">
            </div>




            <div class="form-group">

                <label for="image">Image</label>

                <input type="file"
                class="form-control @error('image') is-invalid @enderror"
                name="image"
                value = "{{old('image')}}"
                id="image">


                @error('image')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>


            <div class="form-group">
                <button class="btn btn-success" type="submit">Add Post</button>
            </div>
        </form>
    </div>

</div>
@endsection


@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script>
        flatpickr("#published_at", {
            enableTime: true
        });



        $(document).ready(function() {
    $('.select2').select2();
});

    </script>
@endsection

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.0/flatpickr.min.css"> --}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/css/select2.min.css">
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app');

@section('content')

<div class="card">
    <div class="card-header">Edit Post</div>

    <div class="card-body">
        <form action="{{ route('posts.update',$post->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">

                <label for="title">Title</label>

                <input type="text"
               value = "{{ old('title',$post->title) }}"
                class="form-control @error('title') is-invalid @enderror"
                value = "{{old('title')}}"
                name="title" id="title">

                @error('title')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>


            <div class="form-group">

                <label for="name">Excerpt</label>

                <textarea
                name="excerpt"
                id="excerpt"
                rows="4"
                class="form-control @error('excerpt') is-invalid @enderror">{{ old('excerpt',$post->excerpt) }}"</textarea>

                @error('excerpt')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>


            <div class="form-group">

                <label for="content">Content</label>

            <input id="content" type="hidden" name="content" value="{{old('content',$post->content)}}">
                <trix-editor input="content" ></trix-editor>
                @error('content')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>

            <div class="form-group">
                <select class="form-control" name="category_id" id="category_id">

                    @foreach($categories as $category)
                     <option value="{{$category->id}}" @if($category->id == $post->category_id)  selected @endif >{{$category->name}}</option>
                    @endforeach

                </select>

                @error('category_id')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>


            <div class="form-group">

                <select class="form-control select2" name="tags[]" id="tags" multiple="multiple">


                    @foreach($tags as $tag)

                     <option value="{{$tag->id}}" {{ in_array($tag->id, $post->tags->pluck('id')->toArray())  ? 'selected' : '' }}>{{$tag->name}}</option>
                    @endforeach

                </select>

                @error('tags')
                    <p class="text-danger">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">

                <label for="published_at">Published At</label>

                <input type="text"
                value = "{{old('published_at',$post->published_at)}}"
                class="form-control"
                name="published_at" id="published_at">

            </div>


            <div class="form-group">
            <img src="{{asset('storage/' . $post->image)}}" alt="post-image" width=100%>
            </div>

            <div class="form-group">

                <label for="image">Image</label>

                <input type="file"
                class="form-control @error('image') is-invalid @enderror"
                name="image"
                value = "{{old('image'),$post->image}}"
                id="image">


                @error('image')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>


            <div class="form-group">
                <button class="btn btn-success" type="submit">Update Post</button>
            </div>
        </form>
    </div>

</div>
@endsection

@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script>
        flatpickr("#published_at", {
            enableTime: true
        });



        $(document).ready(function() {
    $('.select2').select2();
});

    </script>
@endsection

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    {{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.0/flatpickr.min.css"> --}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-beta.1/css/select2.min.css">
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-end mb-3">
    <a href="{{ route('posts.create') }}" class="btn btn-primary">Add Posts</a>
</div>

<div class="card">
    <div class="card-header">Posts</div>
    <div class="card-body">
        {{-- Table to show is to be created here! --}}
        @if(!$posts->count() > 0)
            <h5>Nothing to show!!</h5>
         @else
            <table class="table table-bordered" style="word-wrap: break-word">
                <thead>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    <th>Author</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td><img src="{{asset('storage/'.$post->image)}}" alt="Post Image" width="100" height="100"></td>
                            <td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">{{$post->title}}</td>
                            <td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">{{$post->excerpt}}</td>
                            <td>{{$post->category->name}}</td>
                            <td>{{$post->author->name}}</td>
                            <td>
                                <a href="{{route('posts.edit',$post)}}" class="btn btn-warning btn-sm">Edit</a>
                                <a href="" class="btn btn-danger btn-sm"
                                onclick="displayModalForm({{$post}})"

                                data-toggle="modal"
                                data-target="#deleteModal">Trash</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    </div>
    <div class="card-footer">
        {{$posts->links()}}
    </div>
</div>

{{-- DELETE MODAL --}}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form action="" method="POST" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
                <p>Are you sure you want to delete Post</p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
        </div>
    </div>
  </div>
{{-- END DELETE MODAL --}}
@endsection



@section('page-level-scripts')
    <script type= "text/javascript">
    // page-level-scripts goes here

    function displayModalForm($post){
        let $url = '/trash/' + $post.id;
        $('#deleteForm').attr('action',$url);
    }
    </script>
@endsection

resources/views/posts/trashed.blade.php
@extends('layouts.app')

@section('content')

<div class="d-flex justify-content-end mb-3">
    <a href="{{ route('posts.create') }}" class="btn btn-primary">Add Posts</a>
</div>

<div class="card">
    <div class="card-header">Trashed Posts</div>
    <div class="card-body">
        {{-- Table to show is to be created here! --}}
        @if(!$posts->count() > 0)
            <h5>Nothing to show!!</h5>
         @else
            <table class="table tale-bordered" style="word-wrap: break-word">
                <thead>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach($posts as $post)
                        <tr>
                            <td><img src="{{asset('storage/'.$post->image)}}" alt="Post Image" width="200"></td>
                            <td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">{{$post->title}}</td>
                            <td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">{{$post->excerpt}}</td>

                            <td style="word-wrap: break-word;min-width: 160px;max-width: 160px;">{{$post->content}}</td>
                            <td>
                                <form action="{{route('posts.restore',$post->id)}}" method="POST">
                                @method('PUT')
                                @csrf

                                <button type="submit" class="btn btn-sm btn-primary">Restore</button>
                                </form>

                                <a href="" class="btn btn-danger btn-sm"
                                onclick="displayModalForm({{$post}})"

                                data-toggle="modal"
                                data-target="#deleteModal">Delete</a>


                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif
    </div>
    <div class="card-footer">

        {{ $posts->links() }}
    </div>
</div>

{{-- DELETE MODAL --}}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form action="" method="POST" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
                <p>Are you sure you want to delete Post</p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
        </div>
    </div>
  </div>
{{-- END DELETE MODAL --}}
@endsection



@section('page-level-scripts')
    <script type= "text/javascript">
    // page-level-scripts goes here

    function displayModalForm($post){

        let $url = '/posts/' + $post.id;
        $('#deleteForm').attr('action',$url);
    }
    </script>
@endsection

{{-- //tp files --}}
{{-- @section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
        $(document).ready(function(){
        });
        $('.select2').select2();
    </script>
@endsection

@section('page-level-styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection --}}