routes/web.php
<?php

use App\Http\Controllers\categoriesController;
use App\Http\Controllers\postsController;
use App\Http\Controllers\usersController;
use App\Http\Controllers\WelcomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/blog/category/{category}', 'WelcomeController@category')->name('blogs.category');
Route::get('/blog/tag/{tag}', 'WelcomeController@tag')->name('blogs.tag');
Route::get('/blog/post/{post}', 'WelcomeController@post')->name('blogs.post');

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('categories', 'categoriesController');
    Route::resource('posts', 'postsController');
    Route::resource('tags', 'tagsController');

    // Route for soft delete:

    Route::delete('/trash/{post}', 'postsController@trash')->name('posts.trash');

    // index of trashes posts

    Route::get('/trashed', 'postsController@trashed')->name('posts.trashed');

    // restore

    Route::put('/restore/{post}', 'postsController@restore')->name('posts.restore');
});


Route::middleware(['auth', 'verifyAdmin'])->group(function () {
    Route::get('/users', 'usersController@index')->name('users.index');
    Route::put('/users/{user}/make-admin', 'usersController@makeAdmin')->name('users.make-admin');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected  $fillable = ['name'];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/categoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;
use Illuminate\Http\Request;

class categoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::all();
        return view('categories.index', compact([
            'categories'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        // to store the data in database we have to follow 3 steps:
        // 1. To validate the data ->done (we validated the data using Request class)

        // 2. Store the data in database
        Category::create([
            'name' => $request->name
        ]);

        // Session set something and then return the view:
        session()->flash('success', 'Category Added Successfully!');
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        // since category has only one field we do not show category individually

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
        return view('categories.edit', [
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        //
        $category->name = $request->input('name');
        $category->save();
        session()->flash('success', "Category updated successfully");
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
        if ($category->posts->count() > 0) {
            session()->flash('error', 'This category can not be deleted as some posts are associated with it');
            return redirect()->back();
        }
        $category->delete();
        session()->flash('success', "Category Deleted Successfully");
        return redirect(route('categories.index'));
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app');

@section('content')

<div class="card">
    <div class="card-header">Add Category</div>

    <div class="card-body">
        <form action="{{route('categories.store')}}" method="POST">
            @csrf

            <div class="form-group">

                <label for="name">Name</label>

                <input type="text"
                class="form-control @error('name') is-invalid @enderror"
                name="name" id="name">

                @error('name')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>

            <div class="form-group">
                <button class="btn btn-success" type="submit">Add Category</button>
            </div>
        </form>
    </div>

</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app');

@section('content')

<div class="card">
    <div class="card-header">Edit Category</div>

    <div class="card-body">
        <form action="{{route('categories.update',$category->id)}}" method="POST">
            @csrf
            @method('PUT')

            <div class="form-group">

                <label for="name">Name</label>

                <input type="text"
                class="form-control @error('name') is-invalid @enderror"
                name="name" id="name"
                value="{{old('name',$category->name)}}">

                @error('name')
                    <p class="text-danger">{{$message}}</p>
                @enderror

            </div>

            <div class="form-group">
                <button class="btn btn-success" type="submit">Update Category</button>
            </div>
        </form>
    </div>

</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')



@section('content')

@include('layouts._message')
<div class="d-flex justify-content-end mb-3">
    <a href="{{ route('categories.create') }}" class="btn btn-primary">Add Category</a>
</div>

<div class="card">
    <div class="card-header">categories</div>
    <div class="card-body">
        {{-- Table to show is to be created here! --}}

        <table class="table tale-bordered">
            <thead>
                <th>Name</th>
                <th>Actions</th>
            </thead>
            <tbody>
                @foreach($categories as $category)
                    <tr>
                        <td>{{$category->name}}</td>
                        <td><a href="{{route('categories.edit',$category->id)}}" class="btn btn-warning btn-sm">Edit</a>
                        <a href="#" onclick="displayModalForm({{$category}})"
                         class="btn btn-danger btn-sm"

                            data-toggle="modal"
                            data-target="#deleteModal">Delete</a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

{{-- DELETE MODAL --}}

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form action="" method="POST" id="deleteForm">
            @csrf
            @method('DELETE')
            <div class="modal-body">
                <p>Are you sure you want to delete category</p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
        </div>
    </div>
  </div>
{{-- END DELETE MODAL --}}
@endsection



@section('page-level-scripts')
  <script type= "text/javascript">


    function hel(){
        console.log('hel');
    }
    function displayModalForm($category)
    {
        var url = '/categories/' + $category.id;
        $('#deleteForm').attr('action',url);
    }
</script>
@endsection